avatar = "images/avatar.jpg"
motto = "去码头整点薯条"
author = "Causality"
email = "yeqiu.play@gmail.com"

numPostsIndex = 5
numPostsChapter = 2

# # gitalk
# [gitalk]
# clientID = '9a04c6b451fbce76511d'
# clientSecret = '430c540c77ecd6b59749c60f0341c057bd5320a0'
# repo = 'Causa1ity.github.io'
# owner = 'Causa1ity'
# admin = 'Causa1ity'
