baseURL = "https://causality.top"
languageCode = "zh-cn"
title = "Noth"
theme = "noth"
# theme = "github.com/causa1ity.hugo-theme-noth"

# 摘要
summaryLength = 100
hasCJKLanguage = true

# 分页数
paginate = 7

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[build]
useResourcesCache = "always"
