avatar = "/images/avatar.jpg"
motto = "去码头整点薯条"
author = "Causality"
email = "yeqiu.play@gmail.com"
github = "https://github.com/causa1ity"
background = "/images/background-1.jpg"

# gitalk
[gitalk]
clientID = '9a04c6b451fbce76511d'
clientSecret = '430c540c77ecd6b59749c60f0341c057bd5320a0'
repo = 'Causa1ity.github.io'
owner = 'Causa1ity'
admin = 'Causa1ity'
